//http
const HTTP_OPEN = 'HTTP_OPEN';
const HTTP_SUCCESS = 'HTTP_SUCCESS';
const HTTP_FAILED = 'HTTP_FAILED';
const HTTP_RESET = 'HTTP_RESET';

//auth
const FETCH_AUTHORIZE = 'FECTH_AUTHORIZE';
const FETCH_AUTHORIZE_SUCCESS = 'FETCH_AUTHORIZE_SUCCESS';
const FETCH_AUTHORIZE_FAILED = 'FETCH_AUTHORIZE_FAILED';


//loading
const LOADING_SHOW = 'LOADING_SHOW';
const LOADING_HIDE = 'LOADING_HIDE';

const actionTypes = {
  HTTP_OPEN,
  HTTP_SUCCESS,
  HTTP_FAILED,
  HTTP_RESET,
  FETCH_AUTHORIZE,
  FETCH_AUTHORIZE_SUCCESS,
  FETCH_AUTHORIZE_FAILED,
  LOADING_SHOW,
  LOADING_HIDE
}

export default actionTypes;